on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  coverage:
    name: Collect and upload coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, make test-coverage
      run: |
        npm install
        npm run build
        npm run coverage
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
